name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: configure project
        run: |
          npm ci
          cp sample.env .env
        working-directory: ./api

      - name: start docker
        run: docker compose up -d

      - name: wait for db
        run: sleep 5
        working-directory: ./api

      - name: run tests with coverage
        run: npm run test:coverage
        working-directory: ./api

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./api/coverage
          flags: api
          name: api-tests

  api-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: install dependencies
        run: npm ci
        working-directory: ./api

      - name: run lint
        run: npm run lint
        working-directory: ./api

  web-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: install dependencies
        run: npm ci
        working-directory: ./web

      - name: run tests with coverage
        run: npm run test:coverage
        working-directory: ./web

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./web/coverage
          flags: web
          name: web-tests

  web-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: install dependencies
        run: npm ci
        working-directory: ./web

      - name: run lint
        run: npm run lint
        working-directory: ./web
